#!/bin/bash
#
# SnowClash EC2 Deployment Script
# Amazon Linux 2023 + Node.js 22 + PM2 + Nginx + Let's Encrypt
#
# Usage: curl -fsSL https://raw.githubusercontent.com/nalbam/SnowClash/main/scripts/deploy-ec2.sh | bash
#        or: ./deploy-ec2.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
  echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then
  log_error "Please do not run as root. Run as ec2-user."
  exit 1
fi

echo ""
echo "=============================================="
echo "       SnowClash EC2 Deployment Script"
echo "=============================================="
echo ""

# Get domain name
read -p "Enter your domain name (e.g., game.example.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  log_error "Domain name is required!"
  exit 1
fi

# Get email for Let's Encrypt
read -p "Enter your email for Let's Encrypt: " EMAIL
if [ -z "$EMAIL" ]; then
  log_error "Email is required for Let's Encrypt!"
  exit 1
fi

# Confirm settings
echo ""
echo "=============================================="
echo "  Domain: $DOMAIN"
echo "  Email:  $EMAIL"
echo "=============================================="
echo ""
read -p "Continue with these settings? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
  log_warn "Deployment cancelled."
  exit 0
fi

# Installation directory
INSTALL_DIR="/home/ec2-user/SnowClash"
APP_NAME="snowclash"

log_info "Starting deployment..."

# ============================================
# 1. System Update
# ============================================
log_info "Updating system packages..."
sudo dnf update -y

# ============================================
# 2. Install Node.js 22
# ============================================
log_info "Installing Node.js 22..."
curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
sudo dnf install -y nodejs

# Verify Node.js installation
NODE_VERSION=$(node --version)
log_success "Node.js installed: $NODE_VERSION"

# ============================================
# 3. Install PM2
# ============================================
log_info "Installing PM2..."
sudo npm install -g pm2

# Setup PM2 startup script
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user

log_success "PM2 installed"

# ============================================
# 4. Install Nginx
# ============================================
log_info "Installing Nginx..."
sudo dnf install -y nginx

# Enable and start Nginx
sudo systemctl enable nginx
sudo systemctl start nginx

log_success "Nginx installed and started"

# ============================================
# 5. Install Certbot (Let's Encrypt)
# ============================================
log_info "Installing Certbot..."
sudo dnf install -y certbot python3-certbot-nginx

log_success "Certbot installed"

# ============================================
# 6. Install Git
# ============================================
log_info "Installing Git..."
sudo dnf install -y git

# ============================================
# 7. Clone SnowClash Repository
# ============================================
log_info "Cloning SnowClash repository..."
if [ -d "$INSTALL_DIR" ]; then
  log_warn "Directory exists, pulling latest changes..."
  cd "$INSTALL_DIR"
  git pull origin main
else
  git clone https://github.com/nalbam/SnowClash.git "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ============================================
# 8. Install Dependencies and Build
# ============================================
log_info "Installing npm dependencies..."
npm ci --production=false

log_info "Building server..."
npm run build:server

log_info "Building client with domain..."
SERVER_URL="$DOMAIN" npm run build

log_success "Build completed"

# ============================================
# 9. Configure Nginx
# ============================================
log_info "Configuring Nginx..."

sudo tee /etc/nginx/conf.d/snowclash.conf > /dev/null <<EOF
# SnowClash Nginx Configuration
# Generated by deploy-ec2.sh

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}

upstream snowclash_backend {
    server 127.0.0.1:2567;
    keepalive 64;
}

server {
    listen 80;
    server_name $DOMAIN;

    # Redirect HTTP to HTTPS (will be configured by certbot)
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL certificates will be configured by certbot
    # ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # SSL settings
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Static files (client)
    location / {
        root $INSTALL_DIR/public;
        try_files \$uri \$uri/ /index.html;

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    # API endpoints
    location /api {
        proxy_pass http://snowclash_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Colyseus matchmake
    location /matchmake {
        proxy_pass http://snowclash_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # WebSocket connections (Colyseus room IDs)
    location ~ ^/[a-zA-Z0-9_-]+$ {
        proxy_pass http://snowclash_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
EOF

# Remove default nginx config if exists
sudo rm -f /etc/nginx/conf.d/default.conf

# Test Nginx configuration
sudo nginx -t

log_success "Nginx configured"

# ============================================
# 10. Temporary HTTP config for Certbot
# ============================================
log_info "Setting up temporary HTTP config for SSL certificate..."

# Create temporary HTTP-only config for initial certificate
sudo tee /etc/nginx/conf.d/snowclash-temp.conf > /dev/null <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        root $INSTALL_DIR/public;
        try_files \$uri \$uri/ /index.html;
    }
}
EOF

# Disable main config temporarily
sudo mv /etc/nginx/conf.d/snowclash.conf /etc/nginx/conf.d/snowclash.conf.bak

# Reload Nginx
sudo nginx -t && sudo systemctl reload nginx

# ============================================
# 11. Obtain SSL Certificate
# ============================================
log_info "Obtaining SSL certificate from Let's Encrypt..."

sudo certbot certonly --nginx \
  -d "$DOMAIN" \
  --non-interactive \
  --agree-tos \
  --email "$EMAIL" \
  --redirect

# Restore main config and remove temp
sudo rm -f /etc/nginx/conf.d/snowclash-temp.conf
sudo mv /etc/nginx/conf.d/snowclash.conf.bak /etc/nginx/conf.d/snowclash.conf

# Update Nginx config with SSL certificate paths
sudo sed -i "s|# ssl_certificate /etc/letsencrypt|ssl_certificate /etc/letsencrypt|g" /etc/nginx/conf.d/snowclash.conf
sudo sed -i "s|# ssl_certificate_key /etc/letsencrypt|ssl_certificate_key /etc/letsencrypt|g" /etc/nginx/conf.d/snowclash.conf

# Test and reload Nginx
sudo nginx -t && sudo systemctl reload nginx

log_success "SSL certificate obtained"

# ============================================
# 12. Setup Auto-renewal for SSL
# ============================================
log_info "Setting up automatic SSL certificate renewal..."

# Create renewal hook to reload nginx
sudo tee /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh > /dev/null <<EOF
#!/bin/bash
systemctl reload nginx
EOF

sudo chmod +x /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh

# Test renewal (dry run)
sudo certbot renew --dry-run

# Certbot automatically adds a systemd timer, verify it's active
sudo systemctl enable certbot-renew.timer
sudo systemctl start certbot-renew.timer

log_success "Auto-renewal configured"

# ============================================
# 13. Create Environment File
# ============================================
log_info "Creating environment file..."

cat > "$INSTALL_DIR/.env" <<EOF
# SnowClash Production Environment
NODE_ENV=production
PORT=2567
ALLOWED_ORIGINS=https://$DOMAIN
EOF

log_success "Environment file created"

# ============================================
# 14. Start Application with PM2
# ============================================
log_info "Starting SnowClash with PM2..."

cd "$INSTALL_DIR"

# Create PM2 ecosystem file
cat > ecosystem.config.js <<EOF
module.exports = {
  apps: [{
    name: '$APP_NAME',
    script: 'dist/server/index.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 2567,
      ALLOWED_ORIGINS: 'https://$DOMAIN'
    },
    max_memory_restart: '500M',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    error_file: 'logs/error.log',
    out_file: 'logs/out.log',
    merge_logs: true,
    autorestart: true,
    watch: false,
  }]
};
EOF

# Create logs directory
mkdir -p logs

# Stop existing instance if running
pm2 delete "$APP_NAME" 2>/dev/null || true

# Start application
pm2 start ecosystem.config.js

# Save PM2 process list
pm2 save

log_success "SnowClash started with PM2"

# ============================================
# 15. Configure Firewall (if enabled)
# ============================================
log_info "Checking firewall settings..."

if command -v firewall-cmd &> /dev/null; then
  if systemctl is-active --quiet firewalld; then
    sudo firewall-cmd --permanent --add-service=http
    sudo firewall-cmd --permanent --add-service=https
    sudo firewall-cmd --reload
    log_success "Firewall configured"
  fi
fi

# ============================================
# 16. Create Management Scripts
# ============================================
log_info "Creating management scripts..."

# Start script
cat > "$INSTALL_DIR/start.sh" <<EOF
#!/bin/bash
cd $INSTALL_DIR
pm2 start ecosystem.config.js
EOF

# Stop script
cat > "$INSTALL_DIR/stop.sh" <<EOF
#!/bin/bash
pm2 stop $APP_NAME
EOF

# Restart script
cat > "$INSTALL_DIR/restart.sh" <<EOF
#!/bin/bash
pm2 restart $APP_NAME
EOF

# Update script
cat > "$INSTALL_DIR/update.sh" <<EOF
#!/bin/bash
cd $INSTALL_DIR
git pull origin main
npm ci --production=false
npm run build:server
SERVER_URL="$DOMAIN" npm run build
pm2 restart $APP_NAME
echo "Update completed!"
EOF

# Logs script
cat > "$INSTALL_DIR/logs.sh" <<EOF
#!/bin/bash
pm2 logs $APP_NAME
EOF

# Status script
cat > "$INSTALL_DIR/status.sh" <<EOF
#!/bin/bash
echo "=== PM2 Status ==="
pm2 status
echo ""
echo "=== Nginx Status ==="
sudo systemctl status nginx --no-pager
echo ""
echo "=== SSL Certificate ==="
sudo certbot certificates
EOF

chmod +x "$INSTALL_DIR"/*.sh

log_success "Management scripts created"

# ============================================
# Complete!
# ============================================
echo ""
echo "=============================================="
echo -e "${GREEN}  Deployment Complete!${NC}"
echo "=============================================="
echo ""
echo "  Your game is available at:"
echo -e "  ${BLUE}https://$DOMAIN${NC}"
echo ""
echo "  Management commands:"
echo "    ./start.sh   - Start the server"
echo "    ./stop.sh    - Stop the server"
echo "    ./restart.sh - Restart the server"
echo "    ./update.sh  - Pull latest and rebuild"
echo "    ./logs.sh    - View application logs"
echo "    ./status.sh  - Check status"
echo ""
echo "  PM2 commands:"
echo "    pm2 status   - Check process status"
echo "    pm2 logs     - View logs"
echo "    pm2 monit    - Monitor resources"
echo ""
echo "  SSL auto-renewal is configured."
echo "  Certificates will renew automatically."
echo ""
echo "=============================================="
